# CRE project settings for ArcBooks Auto-Attest.
default: &default
  cre-cli:
    don-family: "zone-a"
  rpcs:
    - chain-name: arc-testnet
      url: https://rpc.blockdaemon.testnet.arc.io

staging-settings: *default

production-settings: *default
