staging-settings:
  user-workflow:
    workflow-name: "arcbooks-attest"
  workflow-artifacts:
    workflow-path: "."
    config-path: "./config.json"
    secrets-path: ""

production-settings:
  user-workflow:
    workflow-name: "arcbooks-attest"
  workflow-artifacts:
    workflow-path: "."
    config-path: "./config.json"
    secrets-path: ""
